const SET_SINGER = 'SET_SINGER';
const SET_SONGS = 'SET_SONGS';
const SET_PLAYING_STATE = 'SET_PLAYING_STATE';
const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
const SET_PLAYLIST = 'SET_PLAYLIST';
const SET_SEQUENCELIST = 'SET_SEQUENCELIST';
const SET_PLAY_MODE = 'SET_PLAY_MODE';
const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';

export default {
  SET_SINGER,
  SET_SONGS,
  SET_PLAYING_STATE,
  SET_FULL_SCREEN,
  SET_PLAYLIST,
  SET_SEQUENCELIST,
  SET_PLAY_MODE,
  SET_CURRENT_INDEX,
};
